name: Build

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-gcc:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - run: sudo apt-get install llvm
        - run: make debug CC=gcc
        # - run: ./bin/ansllc -v
        - run: make clean

    build-clang:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - run: sudo apt-get install llvm
        - run: make debug CC=clang
          # - run: ./bin/ansllc -v
        - run: make clean
